POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWM0ODMwODk1NDMyOGY4MDhmYmQwMTViIiwiaWF0IjoxNTQ4MjQwOTg2fQ.EloofKUl6Mv6UUrRmqKfZxqQ09qS-vFrQM3UeoVE6-w

{
  "title": "Test title",
  "author": "John Doe",
}